LLotofacil/Models/ErrorViewModel.cs
using System;

namespace LLotofacil.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LLotofacil/Controllers/HomeController.cs
using LLotofacil.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace LLotofacil.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LLotofacil/Controllers/LotofacilConcursoController.cs
using ClassLibraryLoterica.Models;
using ClassLibraryService;
using Microsoft.AspNetCore.Mvc;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LLotofacil.Controllers
{
    public class LotofacilConcursoController : Controller
    {
        private readonly ILotofacil concurso;
        public LotofacilConcursoController(ILotofacil concurso)
        {
            this.concurso = concurso;
        }
        [HttpPost]
        public IActionResult Index(int? pagina, int? ConcursoID)
        {

            List<Lotofacil> listLotofacil = new List<Lotofacil>();
            listLotofacil = concurso.GetConcursoID(ConcursoID).ToList();

            int paginaTamanho1 = 10;
            int paginaNumero1 = (pagina ?? 1);

            return View(listLotofacil.ToPagedList(paginaNumero1, paginaTamanho1));
        }

        public IActionResult Index(int? pagina, int ConcursoID)
        {
            List<Lotofacil> listLotofacil = new List<Lotofacil>();
            if(ConcursoID != null)
            {
                listLotofacil = concurso.GetAllConcursos().ToList();
                int paginaTamanho = 10;
                int paginaNumero = (pagina ?? 1);

                return View(listLotofacil.ToPagedList(paginaNumero, paginaTamanho));
            }

            return View();
           
        }
       
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Lotofacil lotofacil = concurso.GetConcurso(id);

            if (lotofacil == null)
            {
                return NotFound();
            }

            return View(lotofacil);
        }
        public IActionResult Simular()
        {

            return View();
        }

        [HttpPost]
        public IActionResult Simular(int? Dezena_01, int? Dezena_02, int? Dezena_03, int? Dezena_04, int? Dezena_05,
                                    int? Dezena_06, int? Dezena_07, int? Dezena_08, int? Dezena_09, int? Dezena_10,
                                    int? Dezena_11, int? Dezena_12, int? Dezena_13, int? Dezena_14, int? Dezena_15)
        {

            //ViewBag para mostrar na tela as dezenas digitadas
            ViewBag.Dezena_01 = Dezena_01;
            ViewBag.Dezena_02 = Dezena_02;
            ViewBag.Dezena_03 = Dezena_03;
            ViewBag.Dezena_04 = Dezena_04;
            ViewBag.Dezena_05 = Dezena_05;
            ViewBag.Dezena_06 = Dezena_06;
            ViewBag.Dezena_07 = Dezena_07;
            ViewBag.Dezena_08 = Dezena_08;
            ViewBag.Dezena_09 = Dezena_09;
            ViewBag.Dezena_10 = Dezena_10;
            ViewBag.Dezena_11 = Dezena_11;
            ViewBag.Dezena_12 = Dezena_12;
            ViewBag.Dezena_13 = Dezena_13;
            ViewBag.Dezena_14 = Dezena_14;
            ViewBag.Dezena_15 = Dezena_15;

            List<Lotofacil> listLotofacil = new List<Lotofacil>();
            listLotofacil = concurso.GetPontos(Dezena_01, Dezena_02, Dezena_03, Dezena_04, Dezena_05,
                                                       Dezena_06, Dezena_07, Dezena_08, Dezena_09, Dezena_10,
                                                       Dezena_11, Dezena_12, Dezena_13, Dezena_14, Dezena_15).ToList();


            if (listLotofacil == null)
            {
                return NotFound();
            }

            return View(listLotofacil);
        }
    }
}

LLotofacil/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

LLotofacil/Views/LotofacilConcurso/Details.cshtml
@model ClassLibraryLoterica.Models.Lotofacil

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Lotofacil</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ConcursoID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ConcursoID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Data)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Data)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dezena_01)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dezena_01)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dezena_02)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dezena_02)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dezena_03)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dezena_03)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dezena_04)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dezena_04)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dezena_05)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dezena_05)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dezena_06)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dezena_06)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dezena_07)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dezena_07)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dezena_08)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dezena_08)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dezena_09)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dezena_09)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dezena_10)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dezena_10)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dezena_11)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dezena_11)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dezena_12)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dezena_12)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dezena_13)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dezena_13)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dezena_14)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dezena_14)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dezena_15)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dezena_15)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Arrecadacao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Arrecadacao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ganhadores)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ganhadores)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Retornar</a>
</div>

LLotofacil/Views/LotofacilConcurso/Index.cshtml
@model PagedList.IPagedList<ClassLibraryLoterica.Models.Lotofacil>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
@using (Html.BeginForm("Index", "LotofacilConcurso", FormMethod.Post))
{
    <p style="color:red">@ViewBag.Erro</p>

    <tr>
        <th colspan="2" align="center">Digite o jogo:</th>
    </tr>

    <td>
        <input type="number" name="ConcursoID" size="1" />
    </td>
    <td><input type="submit" value="Enviar" /></td>
}
<div>
    <a asp-action="Index">Listar todos</a>
</div>

<table class="table" id="tblConcursos">
    <thead>
        <tr>
            <th>
                Concurso
            </th>
            <th>
                Data
            </th>
            <th>
                Bola01
            </th>
            <th>
                Bola02
            </th>
            <th>
                Bola03
            </th>
            <th>
                Bola04
            </th>
            <th>
                Bola05
            </th>
            <th>
                Bola06
            </th>
            <th>
                Bola07
            </th>
            <th>
                Bola08
            </th>
            <th>
                Bola09
            </th>
            <th>
                Bola10
            </th>
            <th>
                Bola11
            </th>
            <th>
                Bola12
            </th>
            <th>
                Bola13
            </th>
            <th>
                Bola14
            </th>
            <th>
                Bola15
            </th>
            <th>
                Arrecadação
            </th>
            <th>
                Ganhadores
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null)
        {
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ConcursoID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Data)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Dezena_01)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Dezena_02)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Dezena_03)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Dezena_04)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Dezena_05)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Dezena_06)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Dezena_07)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Dezena_08)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Dezena_09)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Dezena_10)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Dezena_11)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Dezena_12)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Dezena_13)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Dezena_14)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Dezena_15)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Arrecadacao)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Ganhadores)
                    </td>
                    <td>
                        @Html.ActionLink("Details", "Details", new { id = item.ConcursoID })
                    </td>
                </tr>
            }
        }
    </tbody>
</table>
<div>

        Página @(Model.PageCount< Model.PageNumber ? 0 : Model.PageNumber)
    of @Model.PageCount

    @if (Model.HasPreviousPage)
    {
        @Html.ActionLink("<<", "Index", new { pagina = 1, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter })
        @Html.Raw(" ");
        @Html.ActionLink("< Anterior", "Index", new { pagina = Model.PageNumber - 1, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter })
    }
    else
    {
        @:<<
        @Html.Raw(" ");
        @:< Anterior
    }

    @if (Model.HasNextPage)
    {
        @Html.ActionLink("Próxima >", "Index", new { pagina = Model.PageNumber + 1, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter })
        @Html.Raw(" ");
        @Html.ActionLink(">>", "Index", new { pagina = Model.PageCount, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter })
    }
    else
    {
        @:Próxima >
        @Html.Raw(" ")
        @:>>
    }


</div>
@section Scripts{
    <!--<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#tblConcursos').DataTable();
        });
    </script>-->
}

LLotofacil/Views/LotofacilConcurso/Simular.cshtml
@model IEnumerable<ClassLibraryLoterica.Models.Lotofacil>

@{
    ViewData["Title"] = "Simular";
}

<h1>Simular</h1>

<h4>Lotofácil</h4>
<hr />

@using (Html.BeginForm("Simular", "LotofacilConcurso", FormMethod.Post))
{
    <p style="color:red">@ViewBag.Erro</p>
    <table cellpadding="0" cellspacing="0">
        <tr>
            <th colspan="2" align="center">Digite o jogo:</th>
        </tr>
        <tr>
            <td>
                <input type="number" name="Dezena_01" size="1" min="1" max="06" />
            </td>
            <td>
                <input type="number" name="Dezena_02" size="1" min="2" max="09" />
            </td>
            <td>
                <input type="number" name="Dezena_03" size="1" min="3" max="11" />
            </td>
            <td>
                <input type="number" name="Dezena_04" size="1" min="4" max="13" />
            </td>
            <td>
                <input type="number" name="Dezena_05" size="1" min="5" max="14" />
            </td>
        </tr>
        <tr>
            <td>
                <input type="number" name="Dezena_06" size="1" min="6" max="16"/>
            </td>
            <td>
                <input type="number" name="Dezena_07" size="1" min="7" max="17"/>
            </td>
            <td>
                <input type="number" name="Dezena_08" size="1" min="8" max="18"/>
            </td>
            <td>
                <input type="number" name="Dezena_09" size="1" min="9" max="19"/>
            </td>
            <td>
                <input type="number" name="Dezena_10" size="1" min="10" max="20"/>
            </td>
        </tr>
        <tr>
            <td>
                <input type="number" name="Dezena_11" size="1" min="12" max="21"/>
            </td>
            <td>
                <input type="number" name="Dezena_12" size="1" min="13" max="22"/>
            </td>
            <td>
                <input type="number" name="Dezena_13" size="1" min="15" max="23"/>
            </td>
            <td>
                <input type="number" name="Dezena_14" size="1" min="14" max="24"/>
            </td>
            <td>
                <input type="number" name="Dezena_15" size="1" min="18" max="25"/>
            </td>
        </tr>
        <tr>
            <td><input type="submit" value="Enviar" /></td>
        </tr>
    </table>
@if(Model != null)
{ 
    <h4>Dezenas digitadas:</h4>
    <table>
        <tr>
            <td>
                <p>@ViewBag.Dezena_01</p>
            </td>
            <td>
                <p>-</p>
            </td>
            <td>
                <p>@ViewBag.Dezena_02</p>
            </td>
            <td>
                <p>-</p>
            </td>
            <td>
                <p>@ViewBag.Dezena_03</p>
            </td>
            <td>
                <p>-</p>
            </td>
            <td>
                <p>@ViewBag.Dezena_04</p>
            </td>
            <td>
                <p>-</p>
            </td>
            <td>
                <p>@ViewBag.Dezena_05</p>
            </td>
            <td>
                <p>-</p>
            </td>
            <td>
                <p>@ViewBag.Dezena_06</p>
            </td>
            <td>
                <p>-</p>
            </td>
            <td>
                <p>@ViewBag.Dezena_07</p>
            </td>
            <td>
                <p>-</p>
            </td>
            <td>
                <p>@ViewBag.Dezena_08</p>
            </td>
            <td>
                <p>-</p>
            </td>
            <td>
                <p>@ViewBag.Dezena_09</p>
            </td>
            <td>
                <p>-</p>
            </td>
            <td>
                <p>@ViewBag.Dezena_10</p>
            </td>
            <td>
                <p>-</p>
            </td>
            <td>
                <p>@ViewBag.Dezena_11</p>
            </td>
            <td>
                <p>-</p>
            </td>
            <td>
                <p>@ViewBag.Dezena_12</p>
            </td>
            <td>
                <p>-</p>
            </td>
            <td>
                <p>@ViewBag.Dezena_13</p>
            </td>
            <td>
                <p>-</p>
            </td>
            <td>
                <p>@ViewBag.Dezena_14</p>
            </td>
            <td>
                <p>-</p>
            </td>
            <td>
                <p>@ViewBag.Dezena_15</p>
            </td>
        </tr>
    </table>
}
}

<div>
    <h4>Resultado</h4>
    <hr />

    <table class="table" id="tblConcursos">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ConcursoID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Data)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Dezena_01)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Dezena_02)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Dezena_03)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Dezena_04)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Dezena_05)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Dezena_06)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Dezena_07)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Dezena_08)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Dezena_09)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Dezena_10)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Dezena_11)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Dezena_12)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Dezena_13)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Dezena_14)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Dezena_15)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Arrecadacao)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Ganhadores)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Total)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TotalPar)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TotalImpar)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TotalPrimo)
                </th>
            </tr>
        </thead>
        <tbody>

            @if (Model != null)
            {

                @foreach (var item in Model)
                {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ConcursoID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Data)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Dezena_01)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Dezena_02)

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Dezena_03)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Dezena_04)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Dezena_05)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Dezena_06)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Dezena_07)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Dezena_08)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Dezena_09)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Dezena_10)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Dezena_11)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Dezena_12)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Dezena_13)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Dezena_14)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Dezena_15)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Arrecadacao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ganhadores)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Total)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TotalPar)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TotalImpar)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TotalPrimo)
                </td>
            </tr>
                }
            }
        </tbody>
    </table>

    <a asp-action="Index">Retornar</a>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LLotofacil/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LLotofacil</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LLotofacil</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LotofacilConcurso" asp-action="Index">Resultados</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LotofacilConcurso" asp-action="Simular">Simular</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - LLotofacil - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>